
##### with Kraft (image docker test)###################
services:
  kafka:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka
      - KRAFT_CREATE_TOPICS=topic-a,topic-b,topic-c
      - KRAFT_PARTITIONS_PER_TOPIC=3
      - KRAFT_AUTO_CREATE_TOPICS=true
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:29093
      - KAFKA_LOG_DIRS=/tmp/kafka-logs
      - KAFKA_LOG_RETENTION_MS=-1  # indefini ( ms)
      - KAFKA_LOG_RETENTION_BYTES=1073741824  # 1 Go (optionnel, définit la taille limite)
      - KAFKA_LOG_CLEANUP_POLICY=delete  # Supprimer les messages après la rétention





